### PR TITLE
Fix commonjs exports

### PR DESCRIPTION
**Pull request by vovkasm**
Fixed: #1266 and facebook/react-native#22863

### CODE REVIEW

**Comment by vovkasm** [comment]
Also same issue: #1265

**Comment by vovkasm** [comment]
Also the tests passed I'm not sure is it right fix in common. Yes it fix RN issue, but should this module be available to direct inclusion from browser environment? May be better solution to split builds and make distinct builds for various targets (node, browser, es modules) and set appropriate entry points in package.json?
What people think? If this is the case, I can rework patch.

**Comment by bvaughn** [comment]
Hm, it seems like this was something I missed/broke when upgrading Webpack 1 -> 4 (PR #1235) and we're just noticing it now because we haven't released `react-devtools-core` since then.

The `libraryTarget` used to be "umd" before that change.

**Comment by bvaughn** [comment]
Just published v3.5.1 with the "umd" change– which seems to fix this issue. So thanks again!

**Pull request closed without merging**
