### PR TITLE
Fix keyboard nav

### PR DESCRIPTION
**Pull request by trueadm**
This should fix the issues in https://github.com/facebook/react-devtools/issues/612

### CODE REVIEW

**Comment by gaearon** [comment]
Seems like there's still a bug:



Reproduces consistently for me on first Workplace UFIAsyncWrapper.

**Comment by bvaughn** [comment]
On facebook.com, clicking on any of the Like/Comment nodes:
screen shot 2017-06-02 at 9 06 29 am

Then up/down arrowing:
skip-null

Temporarily focuses on a "null" node (and hides the focused/selection color) for one up/down arrow press.

**Comment by gaearon** [comment]
Is this a different issue? Seems like the same div.

**Comment by bvaughn** [comment]
Ah! I think you're right. Sorry. I had my comment open/drafting for a while before I submitted it. Hadn't noticed you'd tagged the same thing above. Sorry.

**Comment by gaearon** [comment]
Haha it’s cool 😄 I was wondering if I’m missing an additional detail.

**Comment by bvaughn** [comment]
Filed #786 for the follow-up work. The rest of this looks solid. Let's go!

**Pull request merged**
