### PR TITLE
Chrome extension icon should activate on sites using React #490

### PR DESCRIPTION
**Pull request by deepak-jacob**
Colour icon will show up on pages build with react.

### CODE REVIEW

**Comment by gaearon** [comment]
This looks like a great start, thank you for jumping on this!

I don’t think we’ll want to use this specific detection strategy because we already should have enough information about whether React is on the page by checking if it attached to the hook we expose.

I’ll try to take it from here because I’m keen to get this out today.

**Comment by deepak-jacob** [comment]
Great, thanks for that !

**Comment by gaearon** [comment]
I added popups!

screen shot 2017-04-28 at 5 50 24 pm

screen shot 2017-04-28 at 5 50 09 pm

I hope this will help people figure out how to use the extension.

>Using page_action instead of browser_action so we don't need to have a gray and colour icon.

I had to revert that part because only `browser_action` lets us show a popup even when extension is inactive (which is important for people confused by the `file://` permission issue).

Overall I’m very grateful for you to showing how to do this, and pushing this change through. 👍

**Comment by gaearon** [comment]
Going to get this in, hope the CI passes. I have some troubles running Flow locally but this should work.

**Comment by deepak-jacob** [comment]
I thought do popup tonight ! but thanks for that... yeah definitely helpful

**Pull request merged**
