### PR TITLE
Call teardown() when Panel will unmount

### PR DESCRIPTION
**Pull request by jhen0409**
(Explanation is now [here](https://github.com/facebook/react-devtools/pull/504#issuecomment-278985858))

### CODE REVIEW

**Comment by gaearon** [comment]
Why does it error in the first place? I'd like to fix the cause instead of silencing errors.

**Comment by jhen0409** [comment]
I take a time to check it, looks like it haven't clear all event listeners when `unmount` panel, I got the old `socket` instance:

```js
window.sock = socket;
wall = {
    ...
    send: (data) => {
      // sometimes false, it should got the old socket instance
      console.log(window.sock === socket)
      socket.send(JSON.stringify(data));
    },
   ...
}
```

I updated the PR, call `this.teardown()` when `componentWillUnmount` in Panel will fix the problem, but we may need to avoid send `shutdown` with closed socket, so I still add the `readyState` check.

**Comment by gaearon** [comment]
@jaredly Can you review this please?

**Comment by gaearon** [comment]
LGTM

**Comment by jhen0409** [comment]
@gaearon it seems not built in `react-devtools-core@2.0.5`, I can't seen this patch in the bundle. 😅

**Comment by gaearon** [comment]
Apologies, I probably forgot to rebuild. Should be in 2.0.6.

**Pull request merged**
