### PR TITLE
Specify flow version in package.json

### PR DESCRIPTION
**Pull request by kassens**
This way travis will not use latest and break when flow gets updated.

### CODE REVIEW

**Comment by kassens** [comment]
Assuming this is okay and merging so I can send out a stacked PR. If anyone has concerns about this, I'll fix them in a followup.

**Comment by spicyj** [comment]
Did you mean to leave the unqualified `flow check` as the script? Should be `./node_modules/.bin/flow`, no?

**Comment by spicyj** [comment]
(@kassens ping)

**Comment by kassens** [comment]
@spicyj: `npm run` seems to have `./node_modules/bin` in the path. It passes on Travis which doesn't have a global installed flow. Happy to change back.

**Comment by spicyj** [comment]
I'm just confused about this:

https://github.com/kassens/react-devtools/blob/68d1b90d779ff499af5760afbef75d444a2568cd/.travis.yml#L9

**Comment by kassens** [comment]
Travis has `./node_modules/bin` in the path for the node environment.

This might be the setup for it: https://github.com/travis-ci/travis-cookbooks/blob/7926be063565fac6d53ca99b2df6be976e09e041/cookbooks/nodejs/files/default/profile_entry.sh#L2

**Comment by spicyj** [comment]
Wooah. Got it. Thank you.

**Pull request merged**
