### PR TITLE
Fix #183 - [firefox] Add invertIconForLightTheme: true

### LINKED ISSUE #183: [firefox] Icon is invisible on light theme
Right now, the react tool icon is white, and in light theme, it looks invisible since the background is too light. A simple fix would be adding `invertIconForLightTheme: true` in the tool definition.

### PR DESCRIPTION
**Pull request by nt1m**

### CODE REVIEW

**Comment by spicyj** [comment]
Do you know when your patch will hit stable? I guess adding this doesn't hurt anything until it does though since it already looks wrong…

**Comment by nt1m** [comment]
@spicyj The patch landed in Firefox 43, which is currently in Developer edition, and which will land in stable on 2015-12-15. It's still nice to have this PR merged for Firefox Developer Edition users using React DevTools.

**Comment by spicyj** [comment]
Got it. I was thinking that everyone on developer edition used the dark theme but maybe not…

**Comment by nt1m** [comment]
@spicyj Most people do, but they can still switch on the light theme if they like.

**Pull request merged**
