### PR TITLE
Upgrade to Babel 6

### PR DESCRIPTION
**Pull request by kassens**

### CODE REVIEW

**Comment by spicyj** [comment]
None of the webpack configs needed the stage?

**Comment by kassens** [comment]
This is now moved into a preset and I pushed the config to the babelrc that is shared for all of them (including jest).

**Comment by spicyj** [comment]
I meant: before, .babelrc specified stage 0 but so did the webpack configs. Now only .babelrc does. Were the webpack configs redundant?

**Comment by kassens** [comment]
They might've been redundant. Alternatively, it might be an update that came with `babel-loader` v6 that it reads the `.babelrc`. I tested the plugin and it worked and everything compiled (it didn't without the `.babelrc`)
¯\\\_(ツ)\_/¯

**Comment by iamdustan** [comment]
I think the webpack config was redundant. I’m still using Babel 5.x witg webpack and the only config is in .babelrc.

**Pull request merged**
