### PR TITLE
Fix left right arrow behavior

### PR DESCRIPTION
**Pull request by jobala**
#### What does this PR do
* When the left arrow is clicked on the closing tag, the cursor jumps to the head tag.
* When the right arrow is clicked on the closing tag, it does nothing instead of the cursor
focusing on the last child.

Fixes [783](https://github.com/facebook/react-devtools/issues/783)

### CODE REVIEW

**Comment by gaearon** [comment]
I think it currently breaks collapsing. I can't seem to press "left" on the opening tag to collapse it.

**Comment by trueadm** [comment]
@jobala I just tried your PR out locally and I can't close tags by pressing left anymore on the opening tag (I can on master). Does this happen for you locally too?

**Comment by gaearon** [comment]
I fixed that. Thank you so much for the PR!

**Comment by bvaughn** [comment]
Nice work @jobala !

**Pull request merged**
