### PR TITLE
Detect DEV version of React

### PR DESCRIPTION
**Pull request by gaearon**
Implements https://github.com/facebook/react-devtools/issues/562 as suggested by @mnquintana.

This should detect all supported React versions, with the exception of React 16 (Fiber) for which we’ll need to add explicit support (luckily we can do this easily since it’s not released yet).

It should detect all combinations (no envify + no uglify, envify + no uglify, no envify + uglify). It works by introspecting the `Mount._renderNewRootComponent` source which is present in all React DOM versions, and gives us enough information thanks to a warning (after 15.1) and to the fact that it used to be wrapped into a ReactPerf wrapper in DEV (before 15.1).

What's missing:

* [x] Check for outdated version of React
* [x] Popup for outdated version of React
* [x] A flag on React side to support Fiber
* [x] Fiber support (once that flag on React side is merged)
* [x] Actually test 0.13, 0.14, 15.0, 15.1, 15.2, and 15.4

It looks like this.

screen shot 2017-05-02 at 7 08 27 pm
screen shot 2017-05-02 at 7 08 34 pm

### CODE REVIEW

**Comment by bvaughn** [comment]
How's this?

screen shot 2017-05-02 at 11 36 25 am

Will push as soon as I have permission to.

**Comment by gaearon** [comment]
Looks good. Can you push now?

**Comment by bvaughn** [comment]
Thanks! Pushed.

**Comment by gaearon** [comment]
I did some testing, and it looks good. Going to ship.

**Comment by enapupe** [comment]
Awesome!
Looking god except for that :white_check_mark:  icon that is missing.

ss
```
Google Chrome	56.0.2924.76 (Official Build) (64-bit)
Revision	cc6576b53870d39ddafd3574d951ff36d5f7218e-refs/branch-heads/2924@{#860}
OS	Linux 
JavaScript	V8 5.6.326.42
Flash	25.0.0.148 /home/enapupe/.config/google-chrome/PepperFlash/25.0.0.148/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36

Command Line	/opt/google/chrome/google-chrome --flag-switches-begin --flag-switches-end
Executable Path	/opt/google/chrome/google-chrome
```

**Comment by bvaughn** [comment]
@enapupe I believe this indicates that your OS is missing the U+2705 character in its default sans-serif font. (Can you see it [here](http://graphemica.com/%E2%9C%85)?)

**Comment by enapupe** [comment]
Kind of??

symbol

**Comment by bvaughn** [comment]
Ah, rats. I didn't notice that page was using a different font.
What if you change the element's font to `font-family: sans-serif;` in Chrome's inspector?

**Comment by enapupe** [comment]
Yeah I guess not. That on the image is likely to be provided by a webfont

**Comment by enapupe** [comment]
So yeah, my system doesn't have it. Sorry for the  trouble. Thanks for that!

**Comment by bvaughn** [comment]
No problem at all. I'm still kind of learning my way around this project too so I wasn't sure anyway 😁

**Comment by gaearon** [comment]
Maybe we can just replace this with an equivalent royalty free SVG or something.

**Comment by bvaughn** [comment]
I guess so. The icons aren't really necessary to be honest. The text is sufficient. (IMO the popups aren't meant to be pretty, just practical.)

**Pull request merged**
