### PR TITLE
Chrome dark theme compatibility

### PR DESCRIPTION
**Pull request by jonlunsford**
## What's up?

This PR is in reference to #108. It will make react-devtools usable with Chrome's dark theme by adding a white background color to `frontend/Container.js`.

#### Before: 

react-devtools-before

#### After:

react-devtools-after

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by danielmurray** [comment]
Does chrome allow for the ability to check user settings, e.g. theme coloring?

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jonlunsford** [comment]
Hmmm, that would be great. I couldn't find anything in the API docs, most things are in reference to 'normal' user settings.

**Comment by spicyj** [comment]
Well, this can't hurt. Maybe worth asking one of the Chrome folks on Twitter (Paul Irish?) if it's possible to check the theme.

**Comment by LestaD** [comment]
@jonlunsford white is bad for dark theme!!

**Pull request merged**
