### PR TITLE
Minor grammar update: Fix spelling and update sentence structure.

### PR DESCRIPTION
**Pull request by drewlandis**
Super simple grammar update.

Note: this is my first contribution to a Facebook open source project.  I don't have a FB account, however I did fill out the CLA here: https://code.facebook.com/cla .  Let me know if there are any problems/issues with that.

Thanks!

### CODE REVIEW

**Comment by drewlandis** [comment]
Email sent.

**Comment by drewlandis** [comment]
This is my work email, which had been the primary email address listed on
my github account (drewlandis).  I just changed my primary email to
landis.d@gmail.com and associated my CLA with that email.

Sorry for the confusion.  HTH!

Drew

**Comment by spicyj** [comment]
Thanks

**Comment by spicyj** [comment]
Thanks!

**Pull request merged**
