### PR TITLE
Adds support for values: undefined, NaN, Infinity and -Infinity

### LINKED ISSUE #653: value: NaN being displayed as null
screen shot 2017-04-29 at 11 13 21
screen shot 2017-04-29 at 11 13 27

### PR DESCRIPTION
**Pull request by davidfurlong**
Fixes #653 #582

### CODE REVIEW

**Comment by gaearon** [comment]
Hmm, we might want to be able to change that code (in order to fix more such bugs in the future etc). Are you absolutely sure there are no existing alternatives that are well tested?

If not it would be preferable to keep the source code here (in `packages`).

**Comment by davidfurlong** [comment]
@gaearon I looked fairly thoroughly, though I might have not had the right keywords. 
I too am a bit worried about testing / compatibility. However I am not doing anything radically different than JSON2 already does with null values. Beyond splitting into its own namespace/different package, the whole diff is https://github.com/davidfurlong/JSON-js/commit/9772bd1fbda29e282f8e1536fbcd2c7f66b88780

As for keeping the source code in `packages` I dont think thats necessary & it may be confusing, as its a whole different utility, but I'm fine with that. I can add you as a contributor to the npm package/git repo if you'd like.

**Comment by gaearon** [comment]
>As for keeping the source code in packages I dont think thats necessary & it may be confusing, as its a whole different utility, but I'm fine with that

If it's a core dependency it's fine for it to be here, it's easier to manage issues and do releases that way.

**Comment by davidfurlong** [comment]
Okay I'm modifying my PR to include the code in `packages`, not excited by the amount of lint errors I'm getting 🏖 .

**Comment by davidfurlong** [comment]
@gaearon added it to `packages`, but couldn't understand how you were locally installing the dependencies inside `packages`

**Comment by tyleriguchi** [comment]
@davidfurlong hey I noticed that this is the same issue as the one in [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension/issues/332). That uses a package called [jsan](https://github.com/kolodny/jsan), which does a very similar thing.

**Comment by davidfurlong** [comment]
@tyleriguchi ah yes thats the sort of thing we were looking for. It does not support NaN, Infinity, -Infinity though. It does support functions & circular structures, and recreates Date Objects rather than leaving them as UTC strings, and recreates ES6 Maps & Sets. Its also more performant & yields smaller strings (u for undefined etc.). I think I could also submit a PR to JSAN to support NaN, Infinity, -Infinity values. @gaearon

**Comment by gaearon** [comment]
I'm okay with using something more battle tested if its feature set works well for us (or if we can contribute to fill in the missing pieces).

**Comment by davidfurlong** [comment]
If we swapped to the JSAN package would we still pull the package into `packages` ~ I put in a PR but have yet to hear anything back. I think we should use the JSAN code, but if the author is not going to maintain the package then I think its better to fork into this repo

**Comment by zalmoxisus** [comment]
The feature is available in the upstream. Let me know if there's anything else we should add there. It's worth to mention that the lib is using WeakMap when available, which makes the serialization really fast, and it's production proved on Redux DevTools Extension for more than an year.

**Comment by davidfurlong** [comment]
@zalmoxisus I am going to modify my PR this evening to use JSAN instead

**Comment by davidfurlong** [comment]
Okay two things:

a) test/example/build doesn't seem to `gitignored`. Since I changed the tests, should I commit the built files
b) jsan has a bug where `parse(stringify(undefined))` is `{$jsan: "u"}`. I've reported it and will look at making a PR there before we merge this.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) 🎉 The source code for this rewrite was done in a separate repository and is [being merged into the main React repo](https://github.com/facebook/react/pull/16381).

**Thank you for taking the time to contribute to this extension** 🙇‍♂️

Because this PR is for the version code base, I am closing it. If you'd like to contribute to the new extension, please visit [the new repository](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Developer+Tools%22).

**Pull request closed without merging**
