### PR TITLE
Add maxWidth to SplitPane to fix Firefox resize issue

### LINKED ISSUE #336: Right pane gets pushed off screen
This didn't always happen, but in the last month or so I noticed that there is no horizontal scrolling where the elements are shown, so the right pane (with props) is pushed off screen.  Below are some screenshots:

Completely hidden:
screen shot 2016-02-28 at 6 12 23 pm

Semi-hidden when I make the window really wide:
screen shot 2016-02-28 at 6 12 46 pm

### PR DESCRIPTION
**Pull request by bvaughn**
Fixes #336 (and duplicates #1107 and #1110)

### CODE REVIEW

**Comment by bvaughn** [comment]
Seemed straight forward enough not to require a review. If you'd like to do a point release with this, feel free. I probably can't do this while flying.

**Comment by snow-dev** [comment]
Just one thing, when it gonna be fixed on firefox extension?

**Comment by gaearon** [comment]
I’ll cut a release today

**Comment by classyrancor** [comment]
thanks @gaearon and @bvaughn for fixing this so quickly!

**Comment by snow-dev** [comment]
Thanks it's working fine now, arigato!

**Pull request merged**
