### PR TITLE
Add == $r  for selected node index

### PR DESCRIPTION
**Pull request by dmitrika**
According to the issue #638 I added == $r text, like we have $0 in chrome devtools.
I copied colors from devtools original $0 text, but not sure with naming.

Also could'nt find out how I can cover with tests this feature.
Feel free to point out any nits or mistakes that I have done 👍

### CODE REVIEW

**Comment by gaearon** [comment]
Can you add a screenshot?

**Comment by gaearon** [comment]
While this is not related I would also appreciate if you could find a way to disable this feature in RN DevTools (`packages/react-devtools`). It's not supported there, and the fact that it appears is confusing.

There is an existing system for checking “capabilities” of different shells so maybe you could use this.

**Comment by gaearon** [comment]
Actually never mind my last comment, it works on RN.

**Comment by dmitrika** [comment]
Here gif for this pr:
node index gif

Yeah, didn't thought about RN, actually. Glad, that it's works the same way.

**Comment by dmitrika** [comment]
I resolved conflits with current master branch. Because of the new color schemes I decided to use tag colors for `== $r`.

Example with Eighties:
![== $r in Eighties]
(https://media.giphy.com/media/l4FGjJNxQB9p9BwqI/giphy.gif)

**Comment by gaearon** [comment]
@bvaughn Mind reviewing?

**Comment by bvaughn** [comment]
> I resolved conflits with current master branch. Because of the new color schemes I decided to use tag colors for `== $r`.

I think this looks like a reasonable color choice 😄 

I think I'm seeing a bug in this though, both in Firefox and Chrome, where the `$r` element isn't always updated:
firefox-bug

**Comment by bvaughn** [comment]
Also the `$r` label shows up for the Electron shell, even though `$r` isn't accessible anywhere (that I know of) in that case. Is it accessible? If not, should we hide the label for that (and the plain shell maybe)?

**Comment by gaearon** [comment]
It's accessible in Electron but you need to follow instructions in its README (enable JS debugging).

**Comment by bvaughn** [comment]
Whoops. RTFM ☺ Sorry.

**Comment by bvaughn** [comment]
Well it looks like this PR is good to merge then, since the bug I mention above wasn't introduced in this revision. I'll create a follow up issue for it.

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
