### PR TITLE
Fix Native Styles Editor

### PR DESCRIPTION
**Pull request by ansumanshah**
ReOpen #658
Todo #668

- [x] AutoSize

- [x] Fix Click to edit

- [x] Fix Zero values

- [x] Tab Navigation

- [x] Font Weight Fix

- [x] Box Layout Overlay

### CODE REVIEW

**Comment by gaearon** [comment]
Wow, nice work. 
A few comments.

I think this style is a bit confusing:

screen shot 2017-05-04 at 2 35 30 pm

Maybe if we remove the colon in this case it would be better?

Zero values seem to render as missing:

screen shot 2017-05-04 at 2 36 55 pm

I don't like how the font gets super thin when I edit a value. Can we keep its weight?

screen shot 2017-05-04 at 2 37 16 pm

Navigating with tabs no longer works. We should ensure Tab and Shift+Tab cycle focus through the fields, just like they do in Chrome DevTools.

If I get the window really narrow, the box layout bleeds:

screen shot 2017-05-04 at 2 38 36 pm

It is odd how editing the key moves the value to the right:

screen shot 2017-05-04 at 2 39 05 pm

This is especially annoying because if I click on the value while I’m editing the key, it doesn’t enter the edit mode for the value.

Do you think you can address these concerns and make it more similar to how Chrome handles it?

**Comment by ansumanshah** [comment]
Cool on it.
@gaearon have we finalised on the styling library that we will be using?

**Comment by gaearon** [comment]
I'd like to keep the existing style system in this PR. We can change how we do styles but it's not related to this PR.

**Comment by ansumanshah** [comment]
fzdaozah4a

Just fixed the UI bit.. have not worked on delete and rename of styles, I think we should deal with them in a separate issue.

**Comment by gaearon** [comment]
This is a great start, thanks. Can you look at other issues with style editor next?

For example, it's confusing that RTCView styles are not editable. They should either appear as readonly, or we should completely hide them, and only show styles on View/Text instead.

**Comment by ansumanshah** [comment]
Awesome, my first PR got merged yay!!!
@gaearon I think we should completely hide them from RCTView
Looking into more issues will get back.

**Pull request merged**
