### PR TITLE
New style input on tab

### LINKED ISSUE #794: Pressing <Tab> on last value in RN style editor should add a new style
Currently it doesn’t:

We need to fix it to create a new key-value pair, just like Chrome does.

### PR DESCRIPTION
**Pull request by glennreyes**
Fixes #794:

kapture 2017-06-12 at 15 39 12

### CODE REVIEW

**Comment by bvaughn** [comment]
This looks pretty slick @glennreyes!

There's a UX issue though that I think we should work out.

tab-1

1. Focus on pre-existing `flex` style and tab twice: This will create a new `<input>` which is great.
2. Fill in a key+value and tab again: This will exit the editor. I would expect it to create another new `<input>`.

tab-2

1. Click on a pre-existing style and tab forward and backwards. You're able to tab between all existing styles (and a new style) which is great.
2. Click near the closing "}" to insert a new style. Press Shift+Tab a few times to tab backwards. You're stuck in a loop between the new style key input and the last style's value input. You can't reach previous styles through keyboard navigation.

**Comment by glennreyes** [comment]
Sorry, couldn't find time to move on here 😢 
Maybe somebody can take here over? The idea is to move the logic from blur to keyup.

**Comment by bvaughn** [comment]
That's okay, Glenn. I'll try to find some time to finish it off.

**Comment by sumnerevans** [comment]
@bvaughn , is there any way I can help with this effort?

**Comment by bvaughn** [comment]
Sure, @sumnerevans. If you'd like to just fork Glenn's branch and create a new PR with the changes, please feel free!

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) 🎉 The source code for this rewrite was done in a separate repository and is [being merged into the main React repo](https://github.com/facebook/react/pull/16381).

**Thank you for taking the time to contribute to this extension** 🙇‍♂️

Because this PR is for the version code base, I am closing it. If you'd like to contribute to the new extension, please visit [the new repository](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Developer+Tools%22).

**Pull request closed without merging**
