### PR TITLE
Modify for-in loop to use Object.getOwnPropertyNames, surfacing enume…

### PR DESCRIPTION
**Pull request by tquetano-r7**
…rable properties and avoiding prototype properties

### CODE REVIEW

**Comment by tquetano-r7** [comment]
This PR is a clean redo of PR [293](https://github.com/facebook/react-devtools/pull/293), which had a ton of changes and was months old so it caused regression issues.

**Comment by omeid** [comment]
Any updates on this? I would be happy to help.

**Comment by gaearon** [comment]
Can you test this and post results of how you tested, and what the output looks like before and after? It’s a bit hard to jump on this without the context.

**Comment by gaearon** [comment]
I re-read the thread. I think this change looks good and is similar to what e54919495d3cbfa6cc45573cb9caad1eab4db663 is doing.
LGTM

**Pull request merged**
