### PR TITLE
add clearer instructions to inspect the inspector

### PR DESCRIPTION
**Pull request by aburato**
hope this helps!

### CODE REVIEW

**Comment by gaearon** [comment]
Let's just mention you need to enable file access? Seems simpler.

**Comment by aburato** [comment]
Yes it is! I only realized it afterwards. Sorry ;)

Il ven 17 feb 2017, 15:28 Dan Abramov <notifications@github.com> ha scritto:

**Comment by gaearon** [comment]
Thanks!

**Comment by aburato** [comment]
You're welcome. Hope to contribute in a much more significant manner in the future.

**Pull request merged**
