### PR TITLE
Make ART work

### LINKED ISSUE #160: Integration with non DOM render targets.
I'm doing something similar to react-canvas and react-pixi where the render target is not actually DOM nodes although it somewhat hijacks the react-dom renderer. In my case it's a scene graph that renders to a canvas element using WebGL. When using these devtools with my project I don't see anything below my "Surface" component (the component that contains the canvas element) other than the canvas element. Is there a way to fake it so that my components will show up?

### PR DESCRIPTION
**Pull request by spicyj**
Fixes #160.

image

### CODE REVIEW

**Comment by jaredly** [comment]
Oh interesting. Thanks for fixing this.

**Comment by fsbdev** [comment]
Thanks, any idea what release this will be in?

**Comment by spicyj** [comment]
Planning to push it to the Chrome store this week.

**Comment by fsbdev** [comment]
I just pulled master and it works for my app too but is it also supposed to/did it ever support highlighting ReactART elements when you hover over the node in the treeview, like it does with ReactDOM elements?

**Comment by spicyj** [comment]
No, sorry.

**Pull request merged**
