### PR TITLE
Base16 themes (part 2)

### PR DESCRIPTION
**Pull request by bvaughn**
Builds on PR #698; resolves follow-up items #705. (This PR appears to be larger than it is because it also includes the entirety of #698.)

I think this is a nice state for initial release of themes. Covers the use-case of custom (non-browser-specific) themes as well as the use-case of observing browser devtools settings. Firefox isn't quite there yet (see [1349896](https://bugzilla.mozilla.org/show_bug.cgi?id=1349896)) but I've left an inline comment that should be easy to address as soon as it is.

Included in this PR:
- [x] New themes added for Chrome-dark and Firefox-dark modes. (Firefox theme not yet used, pending in-review [Mozilla issue 1349896](https://bugzilla.mozilla.org/show_bug.cgi?id=1349896).)
- [x] Added new, special 'default' option to drop-down. If selected, devtools will respect Chrome devtools 'default' and 'dark' modes. Other shells (eg Firefox, Electron) will use Chrome default appearance for now.
- [x] Tweaked paddings, font-sizes, and border colors slightly to better match Chrome devtools defaults.
- [x] Removed details pane header text (on the right) based on feedback from @sebmarkbage and @vjeux (and myself).
- [x] Changed the vertical line that connects opening and closing tags in the tree-view to be a solid, light-blue to more closely match Chrome _and_ to let selected state out-rank hover state in terms of coloring. (See gif below.)
- [x] Fixed no props/state style to better match Chrome.

I also did one thing that's somewhat controversial and I'm open to reversing it- but I collapsed the tag-name color and angle brackets to be the same style. This is what Firefox does. It's nice because it allows us to remove a few wrapper `<span>` tags and it makes the Firefox dark theme look better without hurting the Chrome light/dark themes much. That being said, if people prefer the Chrome style- I can revert that part only. 😄 

##### Chrome devtools mode toggling
devtools-theme-toggle-chrome

##### New Firefox (dark) and Chrome (dark) themes
screen shot 2017-05-10 at 9 22 41 pm
screen shot 2017-05-10 at 9 22 57 pm
screen shot 2017-05-10 at 9 35 19 pm

##### New "default" option
screen shot 2017-05-10 at 9 18 03 pm

##### New tag connector line
New tag connector line

##### No props/state panel
screen shot 2017-05-11 at 9 14 09 pm

### CODE REVIEW

**Comment by gaearon** [comment]
This looks like a bug:

screen shot 2017-05-11 at 11 46 31 am

I feel like the font got too small. Let's be at least as large as default Chrome size.

screen shot 2017-05-11 at 11 45 20 am

**Comment by bvaughn** [comment]
> Let's change tags at least same size as in Chrome.

Interesting. I actually _did_ change the tags to match the font-size in my Chrome. And since I've been switching things over to rems, Cmd +/- zooms the devtools in and out pretty nicely. But I'll look more at it.

Ditto for the hole. Don't know how I caused that. :)

**Comment by gaearon** [comment]
Hmm. Maybe it's just a personal perception and I'm not sure how to back it up. But tags have gotten less comfortable for me to read.

**Comment by clarkbw** [comment]
> Firefox isn't quite there yet (see 1349896) but I've left an inline comment that should be easy to address as soon as it is.

The current patch is approved, should go through soon.  This would mean Firefox 56 will ship with this.

**Comment by bvaughn** [comment]
I used Chrome devtools to inspect themselves and realized that they are using 2 different base font sizes for monospace and sans-serif fonts. So I've updated our approach to do the same and I think it lines up nicely now. Check it out:

screen shot 2017-05-11 at 2 59 14 pm

That being said, you can also Cmd +/- to increase or decrease the font size.

**Comment by bvaughn** [comment]
> This looks like a bug:
> screen shot 2017-05-11 at 11 46 31 am

Ah! Collapsing a tag with a lot of attributes and then resizing so it's too small to all fit on a single line... Nice catch! Looks like I need to re-add a `white-space: nowrap;` that was accidentally dropped. 😁

**Comment by bvaughn** [comment]
Okay, I believe all points in this PR have been addressed as well. Thanks!

**Comment by gaearon** [comment]
Hmm. I just merged the other PR, and this is now showing up as a merge conflict.

**Comment by gaearon** [comment]
I just merged master into this branch with `ours` strategy so this branch always wins.

**Comment by gaearon** [comment]
Actually no, this messed up other things.

**Comment by gaearon** [comment]
WTF is GitHub is doing 😞 
I force-pushed, and it just closed PR for me with "Reopen" button disabled.

**Comment by gaearon** [comment]
Merged via https://github.com/facebook/react-devtools/pull/713.

**Comment by bvaughn** [comment]
Aw, poo. Git history got messed up.

Thanks for pushing it through though Dan.

**Pull request closed without merging**
