### PR TITLE
Remove npm-shrinkwrap

### PR DESCRIPTION
**Pull request by kassens**
The shrinkwrap file is a pain to work with:

- it makes it confusing to update modules since npm-shrinkwrap.json silently overrides package.json
- npm-shrinkwrap.json diffs are huge and not really human readable, so there's no benefit in "seeing what changed"

It seems close enough to just specify strict version ranges instead. The
likelihood that something breaks due to a recursive dependency update seems
small compared to the pain the shrinkwrap causes.

### CODE REVIEW

**Comment by spicyj** [comment]
Okay sure.

**Comment by iamdustan** [comment]
Of course that would cause CI to fail 👹

**Comment by gaearon** [comment]
I opened #377 as a successor to this that fixes Travis.

**Comment by kassens** [comment]
Thanks @gaearon!

**Pull request closed without merging**
