### PR TITLE
npm script for bundling chrome extension (WIP)

### PR DESCRIPTION
**Pull request by Tushkiz**

### CODE REVIEW

**Comment by clarkbw** [comment]
Oh very cool!  You might also be interested in this, I wrote a [quick script](https://github.com/clarkbw/npm-package-search/blob/master/bin/generate-manifest) to generate the `manifest.json` file parts of the `package.json` so you can more easily maintain the version number and description in one place.

**Comment by Tushkiz** [comment]
I like this idea of generating `manifest.json` from `package.json`.
To start with let me create a template file, may be `manifest.template.json` and update the PR.

**Comment by Tushkiz** [comment]
@clarkbw I have updated the PR, let me know what do you think.

**Comment by bvaughn** [comment]
PR #802 has just been merged. It's kind of a super-set of this PR, so I'm going to close this one for now. Thanks a bunch for putting this together @Tushkiz!

**Pull request closed without merging**
