### PR TITLE
Fix incorrect URL in warning message for old versions of React

### PR DESCRIPTION
**Pull request by peterjmag**
Addresses facebook/react-devtools#268.

## Todo

- [ ] Tag https://github.com/facebook/react-devtools/tree/329363301da8fad70d1b49f830886c55ed53b1ef as `v0.13.1` (assuming that's the right commit)
- [ ] Create a new (well, old) release
- [ ] Attach the packed extension from https://github.com/peterjmag/react-devtools-issue-228/blob/master/react-devtools-329363301da8.crx

Ping @zpao @jaredly (since they have access to the FB GitHub org)

### CODE REVIEW

**Comment by peterjmag** [comment]
Ah, forgot about Firefox. I assume we can't build an older version for Firefox? If we can, then maybe I should add some more instructions for FF users, but if not, then I can just clarify in the readme that the older version's for Chrome only.

**Comment by spicyj** [comment]
Right, the old version wasn't compatible with Firefox.

**Comment by peterjmag** [comment]
Thanks @spicyj, I've added a note. I'll test all the links once the old release is added and this PR is merged.

**Comment by peterjmag** [comment]
@kassens @spicyj Just going through some of my older open issues. Any updates on this one? I believe it's ready to merge, it just needs a bit of followup from a maintainer once it's in master (see [the checklist above](https://github.com/facebook/react-devtools/pull/290#issue-118015366)).

**Comment by gaearon** [comment]
I’m going through the PRs, and it feels like this has been stale for a while. I appreciate the effort but I’ll close unless somebody is ready to jump on it and provide more context. We’ve recently shipped 15.0, so 0.12 is a really old version by now, and I don’t think it’s worth spending time correcting the mistakes we’ve made with regards to it. Cheers!

**Pull request closed without merging**
