### PR TITLE
Improve loading and error messages

### LINKED ISSUE #650: The React tab stays in DevTools even when switching to a website not using React
Was able to get the react-devtools stuck with the message "Looking for React..."

Steps to reproduce:
* Visit https://www.facebook.com/ in Chrome
* Open the Chrome devtools
* react-devtools icon should be light up and the react tab visible *(as expected)*
* Now click the react tab and it should work *(as expected)*
* Then change the URL to https://www.google.com/
* react-devtools icon "grayed out" *(as expected)*
* react tab is still visible and selected with the message "Looking for React..." ***(possibly an issue)***

Not sure what the correct behavior should be, but possibly:
* Hide the react tab and select the "default" tab in Chrome devtools *(if that's even possible)*, OR
* Provide a different message in the react tab, maybe something similar to what the icon shows when react is unavailable.

### PR DESCRIPTION
**Pull request by samit4me**
fixes #650 

With [`chrome.devtools`](https://developer.chrome.com/extensions/devtools_panels) you can conditionally create a panel and this is exactly what `react-devtools` does, see [main.js](https://github.com/facebook/react-devtools/blob/8667d793916a0b40a84db0ae2f47000aabf9645d/shells/chrome/src/main.js#L30) . Unfortunately, there is no API to remove a panel, so once the **React tab** has been created there is no way to remove it.

In v2.1.3 and maybe earlier, if you visit a website not using React, no **React tab** will show up *(as expected)*. If you then switch to a website using React *(in the same Chrome tab)* the **React tab** will appear *(as expected)*. If you then go back to the site without React *(in the same Chrome tab)* the **React tab** will still be visible and it shows the message "Looking for React...".

This PR changes that message to more closely align with the message from the `react-devtools` icon, see [`not-detected.html`](https://github.com/facebook/react-devtools/blob/60c3e1bfa3ce60a22f1de1f3d8ea2beda3df2a2e/shells/chrome/popups/not-detected.html). This is also similar to what the [`ember-inspector`](https://github.com/emberjs/ember-inspector/blob/1c34df9e8e7f521b380d09d6f7d3af15c650cc78/app/templates/components/not-detected.hbs#L23-L24) does.

[Prettier](https://github.com/prettier/prettier) was used to style the modified JSX.

### CODE REVIEW

**Comment by samit4me** [comment]
Not sure why travis-ci is failing the build, but I've made sure it works locally and it passes linting, testing and typechecking. Any help will be appreciated 👍

**Comment by samit4me** [comment]
After doing some further testing, I noticed that if you navigate between pages with and without React *(with the **React tab** selected)* you can get the new "React not detected" message to show on pages that are using React. This is because React on the **inspectedWindow** has not finished loading.

The [`componentDidUpdate`](https://github.com/facebook/react-devtools/blob/8667d793916a0b40a84db0ae2f47000aabf9645d/frontend/Panel.js#L214-L223) method continually looks for React until it is found and this is why the "React not detected" message can show and then disappear when React is found.

The problem appears to be ***detecting when the page has finished loading***, if that can be figured out there will be no need to continually look for React.

If that's not possible, a quickfix would be to modify the message to read something like:
screen shot 2017-05-01 at 10 09 06 am

Keen to hear your thoughts!

**Comment by gaearon** [comment]
Thanks for PR. Just a heads up—I’ll be busy with other things this week so it will take a me a little while to get back to this repo.

**Comment by samit4me** [comment]
fixes #648 #650 

1. Improve message consistency between Firefox and Chrome.
1. Delay showing the "React not detected" message so the page has a chance to load.
 NEW - *"Looking for React..." > DevTools*
 **VS**
 OLD - *"Looking for React..." > "React was not detected on this page." > DevTools*

**Comment by gaearon** [comment]
Thanks for the PR. I’m sorry I couldn’t get to reviewing it yet, and probably won’t be able for a couple of weeks.

**Pull request merged**
