### PR TITLE
handle undefined element._currentElement.type gracefully.

### PR DESCRIPTION
**Pull request by sdavis-r7**

### CODE REVIEW

**Comment by gaearon** [comment]
When is this the case?

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by sdavis-r7** [comment]
@gaearon  here is snip of the particular element that fires the error.  Have never seen this error until earlier today.

screen shot 2016-05-18 at 12 01 56 pm

**Comment by gaearon** [comment]
Oh, this makes sense. The earlier `} else if (element._stringText) {` check fails because the string is empty. Could you please fix it instead?

**Comment by sdavis-r7** [comment]
@gaearon  done.  Happy to change it if you'd like something different.

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by gaearon** [comment]
Let’s check `element._stringText === 'string'`?

**Comment by gaearon** [comment]
Thanks!

**Comment by spicyj** [comment]
Thanks both of you!

**Comment by sdavis-r7** [comment]
👍 ⛄

**Pull request merged**
