### PR TITLE
Fixes Issue #867 - Hard to copy part of a component name

### PR DESCRIPTION
**Pull request by bryceosterhaus**
I realize this issue already had the "someone is working on this" tag, but that was back in 2017 so I figured it was fair game.

Here is a demo of it working.
react-devtools-node

### CODE REVIEW

**Comment by bvaughn** [comment]
The `Node` component is already so complicated, I'm hesitant to add anything else to it unless it's _necessary_. In this case, right click -> "Copy element name" seems like it solves this same use case?

**Comment by bryceosterhaus** [comment]
@bvaughn, I just picked up the first "good first issue" I saw and saw that the desire was to mimic the interaction in the elements panel. I think its a helpful feature, but its not in dire need since the "right-click -> copy" feature works.

If this isn't added, no big deal, but you should update https://github.com/facebook/react-devtools/issues/867 with the conclusion and close the issue. Might be even worth going through all the "good first issue" labels and making sure they are needed.

**Comment by bvaughn** [comment]
Oh! My apologies then. I had completely forgotten about that issue 😓

Okay then. I'll try to take a look at this and give it some thought sometime soon.

**Comment by bryceosterhaus** [comment]
@bvaughn no rush! I just wanted to contribute back since I have used the devtools so much. Its not a pressing issue for me at all. Just wanted to start with something simple to get my head into the codebase a bit.

Thanks for all your work!

**Comment by bvaughn** [comment]
What do you think of tweaking the style a bit so that it doesn't change the line height?

style-tweak

e.g.
```diff
diff --git a/frontend/Node.js b/frontend/Node.js
index 84069dfcb..f1cf28cfe 100644
--- a/frontend/Node.js
+++ b/frontend/Node.js
@@ -16,6 +16,7 @@ const nullthrows = require('nullthrows').default;
 
 const decorate = require('./decorate');
 const Props = require('./Props');
+const {monospace} = require('./Themes/Fonts');
 const {getInvertedWeak, hexToRgba} = require('./Themes/utils');
 
 import type {Map} from 'immutable';
@@ -320,7 +321,7 @@ class Node extends React.Component<PropsType, StateType> {
           <div style={sharedHeadStyle} {...headEvents}>
             &lt;
             {showCopyableInput ? 
-              <input ref={this._setHeadRef} defaultValue={name} readOnly="readonly" size={name.length} />
+              <input ref={this._setHeadRef} defaultValue={name} readOnly="readonly" size={name.length} style={copyableElementName} />
               : <span ref={this._setHeadRef} style={jsxSingleLineTagStyle} onDoubleClick={onNameDoubleClick}>{name}</span>
             }
             {node.get('key') &&
@@ -375,7 +376,7 @@ class Node extends React.Component<PropsType, StateType> {
         </span>
         &lt;
         {showCopyableInput ? 
-          <input ref={this._setHeadRef} defaultValue={name} readOnly="readonly" size={name.length} />
+          <input ref={this._setHeadRef} defaultValue={name} readOnly="readonly" size={name.length} style={copyableElementName} />
           : <span ref={this._setHeadRef} style={jsxOpenTagStyle} onDoubleClick={onNameDoubleClick}>{name}</span>
         }
 
@@ -523,7 +524,6 @@ const headStyle = ({
 
   return {
     cursor: 'default',
-    borderTop: '1px solid transparent',
     position: 'relative',
     display: 'flex',
     flexShrink: 0,
@@ -553,6 +553,12 @@ const jsxTagStyle = (inverted: boolean, nodeType: string, theme: Theme) => {
   };
 };
 
+const copyableElementName = {
+  border: 'none',
+  boxShadow: '2px 2px 4px rgba(0, 0, 0, 0.25)',
+  fontFamily: monospace.family,
+};
+
 const tagTextStyle = (inverted: boolean, theme: Theme) => ({
   flex: 1,
   color: inverted ? getInvertedWeak(theme.state02) : theme.special06,
@@ -600,7 +606,6 @@ const tailStyle = ({
   const color = isInverted ? theme.state02 : theme.base04;
 
   return {
-    borderTop: '1px solid transparent',
     cursor: 'default',
     paddingLeft: '1rem',
     paddingRight,
```

**Comment by bvaughn** [comment]
One thing I noticed while testing– If you double click a filtered root, it breaks (since `name` is an array of span elements).

whoops

**Comment by bryceosterhaus** [comment]
Those styles look great and I'll fix the issue with `name` being an array. Thanks for the feedback

**Comment by bryceosterhaus** [comment]
Updated the styling and fixed the issue with name being an array. Let me know if this is what you were thinking.

**Pull request merged**
