### PR TITLE
Ignores all logs from electron

### PR DESCRIPTION
**Pull request by prometheansacrifice**
Fix for #702

### CODE REVIEW

**Comment by gaearon** [comment]
Does this keep the output from `update-notifier`? If not we probably want to move its call into `bin`.

**Comment by prometheansacrifice** [comment]
> move its call into bin
I don't understand.

Also, what's `update-notifier`?

**Comment by gaearon** [comment]
See https://github.com/facebook/react-devtools/pull/695. We added this tool to notify users about updates, and we want to keep *that* output. We could move its call to the `bin.js` script you're editing though (so that it doesn't become ignored).

**Comment by prometheansacrifice** [comment]
Got it. Yep. Makes sense. Added a log statement locally and tested. Seems fine. Pushing it as a separate commit for review.

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
