### PR TITLE
Add "trace react updates" to readme

### PR DESCRIPTION
**Pull request by stipsan**
@jaredly something like this?

Related to #337

### CODE REVIEW

**Comment by jaredly** [comment]
:) cool. For the second paragraph I'd probably instead say 

> Why does it trace components that don't actually update? (via shouldComponentUpdate() -> false) 
> This is a limitation of the system used to track updates, and will hopefully change in the future. It doesn't, however, trace the children of components that opt out, as there's no possibility of them updating.

**Comment by MatthewMiele** [comment]
@stipsan I found your commit but trying to find some more information about this feature. Specifically the colours of the box's that show who's updating. Do you know what the colour of the box represents? If so that should be added as well.

**Comment by stipsan** [comment]
OK @jaredly, I'll update it.

@MatthewMiele the color range is from "cold" blue to "hot" red, corresponding to the frequency of update calls.
Cold colours means the updates are infrequent. If you see a lot of red or yellow it may indicate performance optimization is needed :)
I'll add it to the FAQ, no problem!

**Comment by stipsan** [comment]
@jaredly @MatthewMiele updated :)

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
