### PR TITLE
Add permissions for file://

### LINKED ISSUE #172: Chrome devtools don't work on file: URLs
This is presumably because I removed it from the list of permissions… but the old devtools didn't have any permissions listed in manifest.json and did work on file URLs, so maybe we can fix this regression.

### PR DESCRIPTION
**Pull request by kassens**
Fixes #172

### CODE REVIEW

**Comment by spicyj** [comment]
Did you test that this works locally?

**Comment by kassens** [comment]
Yep, it seems to work and it also doesn't appear to ask for extra permissions when updating. Hopefully, that will not be different on the app store.

**Comment by spicyj** [comment]
Sweeeet. Thank you.

**Comment by jimfb** [comment]
@spicyj Does this mean we now want to back out https://github.com/facebook/react/pull/5610 ?

**Comment by spicyj** [comment]
If this works, then yeah.

**Comment by spicyj** [comment]
If this works when it's in the store, then yeah.

**Comment by kassens** [comment]
Only seems to work when it's installed locally and blocked on the store install.

**Comment by jimfb** [comment]
Well, depending on how you define "work": https://github.com/facebook/react-devtools/issues/172#issuecomment-166741417

It "works" if you explicitly enable it, which is a complex interaction that most people will neglect to do.

**Pull request merged**
