### PR TITLE
UI improvements, behaviour closer to native dev tools

### PR DESCRIPTION
**Pull request by pastelsky**
I've tried to introduce a few minor UX / UI improvements  to issues that I found in devtools over the weekend. These include : 

1) Rearranged controls and tweaked UI for a cleaner look.
image

2) Breadcrumbs are now highlighted on hover.
image

2) Replaced `cursor:pointer` with `cursor:default`. Pointers are usually a thing of webpages.

3) Syntax highlighting and colors are tweaked a bit to chrome's design. 

4) Tooltips are now closer to how chrome does them — more readable.
image

5) Code wrapping works in tree-view - better usability when devtools is docked towards the right.
image

6) Hitting `enter` after a editing a field in DataView now closes the field in addition to applying changes (standard behaviour).

If these changes seem to go a lot in one PR, I could break them down into multiple.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by gaearon** [comment]
Let’s split into separate PRs? I think some of these changes are more controversial / would require more iteration than others. Generally it’s best to do small “fixups” in one PR, and significant UI changes in separate PRs.

**Comment by jaredly** [comment]
yup please split. 1 should be its own (biggest visual change). 2-4 can probably go together. 5 probably(?) has enough code that it should be considered separately

**Comment by gaearon** [comment]
#420 and #422 are merged.
Want to send more PRs? 😇 

I’m sorry we were so slow to review.

**Comment by gaearon** [comment]
Going to close this PR, happy to review new ones.

**Pull request closed without merging**
