### PR TITLE
Adds guard for HostComponent name

### PR DESCRIPTION
**Pull request by jakubsadura**
name can be null, replace should be guarded

screen shot 2018-09-26 at 14 57 25

### CODE REVIEW

**Comment by jakubsadura** [comment]
I have just signed Contributor License Agreement

**Comment by bvaughn** [comment]
In what case would a host component name be null? Host components are just identified by strings, so a null value would fail to render anything?

**Comment by jakubsadura** [comment]
Good question, I have an app with few React roots, I'm not able to reproduce the issue right now. As far as I remember I just tried to open React devtool quite soon after opening the app in Electron and came across error being thrown from `name.replace` - I quickly opened this PR and moved forward. I remember that commenting out `name.replace` helped to run the React devtools.

**Comment by bvaughn** [comment]
I'd prefer to hold off on merging this until I better understand the cause. If you see it again, I'd love if you could share more info (or better yet a repro case) with me.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) 🎉 The source code for this rewrite was done in a separate repository and is [being merged into the main React repo](https://github.com/facebook/react/pull/16381).

**Thank you for taking the time to contribute to this extension** 🙇‍♂️

Because this PR is for the version code base, I am closing it. If you'd like to contribute to the new extension, please visit [the new repository](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Developer+Tools%22).

**Pull request closed without merging**
