### PR TITLE
Placeholder -> Suspense

### PR DESCRIPTION
**Pull request by gaearon**
For https://github.com/facebook/react/pull/13799.

### CODE REVIEW

**Comment by gaearon** [comment]
Will release today in the evening unless somebody does it first

**Comment by bvaughn** [comment]
Any reason not to go ahead and merge this (regardless of when the release goes out)?

**Comment by gaearon** [comment]
Not really, except I haven't had time to test it yet.

**Comment by bvaughn** [comment]
Fastest response time ever?

😄 Fair enough though. Looks solid to me.

**Comment by gaearon** [comment]
If you want to test and release I wouldn't mind. :P But it's fine if not too.

**Comment by bvaughn** [comment]
Nah, I'm just GitHub lurking in between activities 😄

**Pull request merged**
