### PR TITLE
Detect duplicated React

### LINKED ISSUE #700: Detect duplicate React and show a different message
It would be cool if, in addition to DEV mode detection, we could detect when there are two instances of ReactDOM on the page.

This issue mentions how we could detect it: https://github.com/facebook/react-devtools/issues/692.

One thing to keep in mind is it's valid to have two different renderers (e.g. ReactDOM + ReactART), but not two instances of one renderer. Not sure if there's an easy way to tell those cases apart, but we can make changes to React if necessary to support that.

### PR DESCRIPTION
**Pull request by chisler**
Resolves #700.

Most popular renderers that affect chrome, except [one](https://github.com/toxicFork/react-three-renderer/), do not inject themselves in DevTools hook as I stated in this [comment](https://github.com/facebook/react-devtools/issues/700#issuecomment-300606157).

**We want to:**
Detect multiple copies of ReactDOM

**On renderer injection we:**
1. Try to filter out all renderers other than ReactDOM.
2. Count injected renderers.
3. More than 1 => report duplication.

Filtering relies on specifics of production builds of ReactDOM Stack v15.\*, v0.14.\* and v0.13.\* and Fiber.

---

Issues:
1. This filtering is not perfect, it's a way to avoid changing `react-dom`, so if you see a better way, it's cool.
1. Current version of  DevTools overwrites build type reported with each consequent renderer injection. Seems like it's better to report all the builds of renderers to cover "valid multiple renderers" case in future.
1. Function [`isReactDOM()`](https://github.com/chisler/react-devtools/blob/detect-duplicated-react/backend/installGlobalHook.js#L144) works similar to [`detectReactBuildType()`](https://github.com/facebook/react-devtools/blob/fae06506c6d9f2397ff602e41dfea9c9e9c54da1/backend/installGlobalHook.js#L23) => mirrors it's need for  higher fault tolerance.

---

Examples:

|  **Detected**  | 
**Filtered out**  |
|---|---|
|  image  | image  |
|  [Website](https://www.astenonline.com/) uses two copies of React: from vendors.js and chatlio.min.80ec1f7e.js.   |   [Website](http://toxicfork.github.io/react-three-renderer-example/#/webgl_geometries) uses two renderers: unminified ReactDOM and unminified  ReactThreeRenderer (which is filtered out) |
| Result: duplicate reported. | Result: unfinified reported. |

### CODE REVIEW

**Comment by chisler** [comment]
Hey guys,

It's been 3 months since I posted it. 

I mean no disrespect for OSS, I'm just wondering if I did something wrong. I'd like to fix this and update the branch for merging.

I mention @gaearon, the author of issue #700.

**Comment by gaearon** [comment]
Hey, I’m sorry we’re not actively reviewing PRs on this repo (or anywhere, really). We’re in churn mode trying to ship React 16 ([announcement](https://github.com/facebook/react/issues/10294), [remaining work to do](https://github.com/facebook/react/issues/8854)). We’ll get back to reviewing stuff once 16 is shipped.

That said this PR looks really great. But I think we should allow multiple renderers to inject themselves. What do you think about adding a string to `inject()` call in React that would pass `id: 'react-dom'` or something like this? Then we could deduplicate them correctly.

**Comment by chisler** [comment]
May be the best possible solution, because it minimizes code-guessing: 
1. Since now inject `react-dom` renderer passing the `id` argument. 
2. Try to detect old versions of `react` by code, as I do now.

I'll be back with this.

Thanks for reaching out! Good luck with shipping the 16. 
And I'd love to help if possible after this one is finished.

**Comment by gaearon** [comment]
Happy to take PRs to React repo adding `id` to the `inject` call.

**Comment by chisler** [comment]
Hey! I made the [PR](https://github.com/facebook/react/pull/10475) to React and updated the branch here.

Tests that fail on my branch with 
```
.../babel-preset-es2015/index.js" provided an invalid property of "name"
```
 fail on `master` as well, at least on my computer.

**Comment by gaearon** [comment]
Can you figure out why it is failing?

**Comment by chisler** [comment]
Yeah, I'd love to. I'll be able to do that in few days:)

**Comment by chisler** [comment]
The errors were provided by 3rd party packages. After reinstalling all the packages in two weeks tests are alright:)

**Comment by gaearon** [comment]
I think the last remaining blocker for me is https://github.com/facebookincubator/create-react-app/issues/3120.

**Comment by chisler** [comment]
Hi. Thanks for the comment and attention, sorry for the delay. I'm glad @tharakawj is already working on this. I'll look into ReactART's injection.

**Comment by chisler** [comment]
_Small note on merging master_ 

Since we now have `deadcode` build type I prioritised `duplicated` over `deadcode` because duplication describes the app as a whole, deadcode — one specific renderer. 

I assume it's the best solution before we could report table of all the checks about each renderer in popup.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) 🎉 The source code for this rewrite was done in a separate repository and is [being merged into the main React repo](https://github.com/facebook/react/pull/16381).

**Thank you for taking the time to contribute to this extension** 🙇‍♂️

Because this PR is for the version code base, I am closing it. If you'd like to contribute to the new extension, please visit [the new repository](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Developer+Tools%22).

**Pull request closed without merging**
