### PR TITLE
[WIP] Update flow fix violations

### PR DESCRIPTION
**Pull request by riseremi**
I've picked up a work by @aarondancer and pushed it further.

Bumped flow to 0.54.1 from 0.46.0, another 130 errors popped out. I managed to fix nearly all of them. Two errors remain:
`node_modules/react-addons-create-fragment/node_modules/fbjs/lib/partitionObjectByKey.js.flow:20`
`node_modules/react-dom/node_modules/fbjs/lib/partitionObjectByKey.js.flow:20`

They are in the `node_modules` so I don't know what to do.

Update: there is an important change in components' props and state type declaration. I've updated many components to the new syntax in this PR.
You can read about it here:
https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627

### CODE REVIEW

**Comment by gaearon** [comment]
You should be able to put them in `[ignore]` section of the Flow config.

**Comment by riseremi** [comment]
Thank you. Updated PR. There are no flow errors and warnings.
I'm afraid I cannot resolve the conflicts by myself. I may break something.

**Comment by gaearon** [comment]
Yea, unfortunately I'm not sure how you could do that since the code must have changed quite a bit since then. 😞 

I think the best option might be for you to merge master into your branch, for every conflict use the version from master, and then fix Flow in those files again until they pass.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) 🎉 The source code for this rewrite was done in a separate repository and is [being merged into the main React repo](https://github.com/facebook/react/pull/16381).

**Thank you for taking the time to contribute to this extension** 🙇‍♂️

Because this PR is for the version code base, I am closing it. If you'd like to contribute to the new extension, please visit [the new repository](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Developer+Tools%22).

**Pull request closed without merging**
