### PR TITLE
Copy all level props for ‘Copy element props’ feature

### PR DESCRIPTION
**Pull request by zinoviev**
PR for https://github.com/facebook/react-devtools/issues/843

### CODE REVIEW

**Comment by suitupalex** [comment]
This helped a lot in grabbing fixtures for some unit tests. Thanks!

**Comment by suitupalex** [comment]
@zinoviev FYI I've rebased your work on the latest master and made sure everything is working again: https://github.com/suitupalex/react-devtools/tree/feature/deep-copy-props

**Comment by zinoviev** [comment]
@suitupalex Do you test final result in web extension? Will be nice if someone other than me approves this is really works. Any chances for review? @gaearon @bvaughn

**Comment by suitupalex** [comment]
@zinoviev yup! I had to fix it because I've been relying on it to capture fixtures. I've verified it still works after the rebase.

**Comment by davezatch** [comment]
Any news on this? Just ran across it in the wild, and ended up setting a breakpoint and doing `copy(props)`, but especially for minified code this would make life a lot easier!

**Comment by zinoviev** [comment]
@davezatch I guess it will wait for review forever, unless someone from React core team need this function for his own

**Comment by bvaughn** [comment]
For what it's worth, the [new DevTools](https://github.com/bvaughn/react-devtools-experimental) (not yet released) has copy-props built in. It seems unlikely that we'll review or merge any non-urgent PRs for the legacy DevTools (this repo) until we've released the new one because we just don't have the bandwidth. (For the most part, I'm the only one working on DevTools, and it's not the only thing I'm working on either.)

**Comment by davezatch** [comment]
Ok, thanks for the update @bvaughn. I don't suppose there's any kind of timeline for the devtools rewrite?

**Comment by bvaughn** [comment]
Not for a final release, no. There's an early preview release you can test drive [on the demo site](https://react-devtools-experimental-chrome.now.sh/) but there are some known bugs.

**Comment by MickeyKay** [comment]
Just chiming in that I would love to see this feature ship! Thanks for working on this 👍

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) 🎉 The source code for this rewrite was done in a separate repository and is [being merged into the main React repo](https://github.com/facebook/react/pull/16381).

**Thank you for taking the time to contribute to this extension** 🙇‍♂️

Because this PR is for the version code base, I am closing it. If you'd like to contribute to the new extension, please visit [the new repository](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Developer+Tools%22).

**Pull request closed without merging**
