### PR TITLE
Devtools for everyone!!!

### LINKED ISSUE #91: Not showing up when inspecting a Chrome app
I’m using React to develop the UI for a [Chrome app](https://developer.chrome.com/apps).

I have installed the [React Chrome Developer Tools](https://facebook.github.io/react/blog/2014/01/02/react-chrome-developer-tools.html), it shows up in Crome dev tools in the browser, but it doesn’t show up when I’m inspecting the Chrome app’s UI.

I imagine this use case may have not been expected/popular, but I’m still wondering if it’d be a way around it.

screen shot 2015-05-20 at 11 21 50 am

### PR DESCRIPTION
**Pull request by jaredly**
Just add `<script src="http://localhost:8097"></script>` to the top of any html file, and magically debug the react running there. (swap out your network-local IP for `localhost` for pages not on your machine)

This works for:
- iframes
- chrome apps
- safari
- mobile safari/chrome/whatever
- embedded webviews
- chrome extensions (need to disable CSP though to eval... could probably fix this at some point)
- like anything

Test Plan:
- `npm run build` in `/shells/electron`
- then `npm start`

Add the script tag to the top of an html file.
Load the html file anywhere.
Debug to your heart's content.

Fixes #91 #424 #76 #320 #350 #163 #98 and probably others

image

### CODE REVIEW

**Comment by jaredly** [comment]
ping @frantic or @spicyj?

**Comment by frantic** [comment]
LGTM!

**Comment by oelmekki** [comment]
> Fixes #91 #424 #76 #320 #350 #163 #98 and probably others

This is epic. 

Thanks a lot Jared, you just made my work on chrome extensions way 
easier :)

**Comment by matthewwithanm** [comment]
woooah

**Comment by kintendo** [comment]
@oelmekki could you explain how were able to get the dev tools to inspect your chrome extension?

**Comment by oelmekki** [comment]
@kintendo I have not, this commit is not yet released :)

It will be in `0.15.5`, or whatever is released after `0.15.4`.

**Comment by kintendo** [comment]
@oelmekki ah! thanks for that. Here I was already trying to get it to work, haha

**Comment by maks** [comment]
@jaredly I'm probably missing something because when I tried this for a chrome (packaged) app I get an error in devtools console:

> Refused to load the script 'http://localhost:8097/' because it violates the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

I used the current master branch as now from this repo and followed instructions in shells/chrome/Readme. The extension loaded ok but I got the above when I included the localhost script in my main html file. So for now it doesn't fix #91 for me.

**Comment by jaredly** [comment]
@maks look up "disable CSP" for your chrome packaged app. then it should work for you

**Comment by maks** [comment]
@jaredly Thansk for the very quick response!
But I think this might be a show stopper for me, as I don't think chrome packaged apps are able to disable CSP.
When I try per docs from (https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing) I get the following next to my Chrome App in chrome://extensions:
There were warnings when trying to install this extension:
'content_security_policy' is only allowed for extensions and legacy packaged apps, but this is a packaged app.

Others have found the same:  http://stackoverflow.com/a/21131034/85472
as "v2" packaged apps are supposed to use "sandboxes" but I think they won't help in this case.

I guess I need to file a bug with Chromium...

**Comment by jaredly** [comment]
hmmmm darn.

**Comment by maks** [comment]
Yes :-(
In case it helps to come up with something in the future this is the [actual docs for CSP for packaged apps](https://developer.chrome.com/apps/contentSecurityPolicy) instead of for extensions which have different restrictions.
As far as I can see though, the things they offer as alternatives on that page won't help here, so I guess for now, no nice devtools for me when using react for chrome packaged app development.

**Pull request merged**
