### PR TITLE
Make Breadcrumb resizable

### PR DESCRIPTION
**Pull request by miklosme**
react-dev-tools-resizable-breadcrumbs

I'm using Breadcrumb a lot, that is my primary view to understand the component tree.

### CODE REVIEW

**Comment by bvaughn** [comment]
I appreciate the effort that's gone into this 😁 It looks cool!

But I think we're moving toward adding _fewer_ elements to the breadcrumbs strip (see #1094) which would make this change unnecessary. Ideally, we'll only show "owners" there. Worst case, we'll show only class/function components (no host nodes).

So unless someone else disagrees strongly, I think we should skip this enhancement 😄

**Comment by miklosme** [comment]
This is how a representative breadcrumb looks like at my work:

screen shot 2018-08-27 at 12 58 23

I never use the treeview, when need to understand the component tree, I'm looking at the breadcrumb, when interested in the props, I use the right pane. The recent [change](https://github.com/facebook/react-devtools/blob/master/frontend/Breadcrumb.js#L126) in styling makes my way of working very difficult.

I might missing the point of treeview. I feel like the actual app is already a treeview, when I need to check siblings, I just use the selector tool.

**Comment by bvaughn** [comment]
It's helpful to see an example of what the breadcrumb view looks like for your app 😄

First, all of the "div", "span", etc. elements will soon be removed– which would save a couple of rows. Once #1094 is implemented, we'll also try to remove everything but the "owners". Even for production mode, where we can't remove owners, we can probably add some special case handling to filter out HOCs (e.g. connect*). These changes should make your breadcrumb list much more manageable.

**Comment by miklosme** [comment]
It's a bit vague to me how will it look like, but sounds very cool, looking forward to it.

Till then I'm using my special build for sure 😎

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html) 🎉 The source code for this rewrite was done in a separate repository and is [being merged into the main React repo](https://github.com/facebook/react/pull/16381).

**Thank you for taking the time to contribute to this extension** 🙇‍♂️

Because this PR is for the version code base, I am closing it. If you'd like to contribute to the new extension, please visit [the new repository](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Developer+Tools%22).

**Pull request closed without merging**
