### PR TITLE
Fix RN Styles Editor

### PR DESCRIPTION
**Pull request by ansumanshah**
#624 #627 
@gaearon Done some basic UI improvement for now
- [ ] Add autosize input as we can see in chrome style editor

Please put forward any other suggestion for the UI
Will try and work with @soul-wish for the UX improvements he suggested [here](https://github.com/facebook/react-devtools/pull/635)

hksbhnzqy9

### CODE REVIEW

**Comment by gaearon** [comment]
This looks much better, thanks!
Can you make the margin between rule and value match the one Chrome uses?

screen shot 2017-05-02 at 3 12 02 pm

**Comment by ansumanshah** [comment]
Was unable to find the exact margin chrome uses. 
Increased my value to 8px and reduced the size of input field also.
Shall I move ahead with the autosize feature?
screenshot

**Comment by jhen0409** [comment]
Just tried this PR, looks like styles are broken by `BoxInspector`:

**Comment by ansumanshah** [comment]
Oops @jhen0409 How can I turn on the box inspector

**Comment by jhen0409** [comment]
@ansumanshah make sure `react-devtools-core` version is `^2.1.0` included in your React Native project, React Native version must be `^0.43`.

**Comment by ansumanshah** [comment]
Yes I have both created a new react-native init project
everything works but not cannot see the inspector yet, is it anything to do with supportsMeasure prop in RNStyle plugin?

**Comment by ansumanshah** [comment]
Matched some styling on inspector box as well and fixed the aligment of values.
screenshot1

**Comment by ansumanshah** [comment]
@jhen0409 Did I do something wrong here?
To resolve the conflicts I simply rebased the current `facebook/master` to my branch and then pushed it.
What's the correct way to do this

**Pull request closed without merging**
